---
title: "STOR 455 Class 4 R Notebook"
output:
  html_document:
    df_print: paged
  pdf_document: default
---

```{r message=FALSE, warning=FALSE}
# message=FALSE, warning=FALSE suppress warnings and messages from appearing in knitted file

library(readr)
library(Stat2Data)

planets <- read_csv("planets.csv")
```


```{r}
plot(Year~Distance, data = planets)
mod1 = lm(Year~Distance, data = planets)
abline(mod1)
```

```{r}
plot(mod1$residuals~mod1$fitted.values)
abline(0, 0)
```

```{r}
# plot(model) provides 4 diagnostic plots. In this class we look at the first two of them.
plot(mod1, 1:2)
```

```{r}
# Use par() to reset displaying formats. Here "mfrow" divides the window into 2 rows and 2 columns to present 4 plots together.
# log() is the logarithm function with base e. Here it is used to transform data.

```


```{r}

```

```{r}
```

The following calculation provides the nonlinear model.

log(Year) =  -0.0034399 + 1.5020611*log(Distance)

Year = e ^(-0.0034399 + 1.5020611(log(Distance))

Year = e ^(-0.0034399) e ^((1.5020611)(log(Distance))

Year = e ^(-0.0034399) e ^(log(Distance ^1.5020611))

Year = e ^(-0.0034399) (Distance^1.5020611)


```{r}
```

Year = 0.996572(Distance^1.5020611)

```{r}

```

```{r}
# A better way to extract model coefficients is by assigning them to an object.
# "summary(mod3)$coefficients" gives a summary matrix of quantities from the fit.
# For a matrix M, use "M[i,j]" to extract the entry in the i-th row and j-th column in M.

```
